<?php
/* @var $this Bitbull_Soisy_Block_Redirect */
?>
<?php $soisyUrl = $this->getRedirectUrl(); ?>
<?php if($soisyUrl): ?>
    <div id="soisy-overlay" class="soisy-overlay" style="display: none;">
        <?php echo $this->__('You are going to be redirected to Soisy website<br />where you will be able to complete your loan request.'); ?>
    </div>
    <script>
        document.observe("dom:loaded", function() {
            var redirectUrl = '<?php echo $soisyUrl; ?>';

            $('soisy-overlay').show();

            setTimeout(function () {
                location.replace(redirectUrl);
            }, 2000);
        });
    </script>
    <style>
        .soisy-overlay {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: 5000;
            background-color: #fff;
            text-align: center;
            padding-top: 200px;
            font-size: 20px;
        }
    </style>
<?php endif; ?>