<?php
/* @var $this Bitbull_Soisy_Block_Redirect */
?>
<div id="soisy-overlay" class="soisy-overlay" style="display: none;">
    <?php echo $this->__('Tra pochi secondi verrai redirezionato sul sito di Soisy<br />dove potrai completare la tua richiesta di finanziamento.'); ?>
</div>
<script>
    document.observe("dom:loaded", function() {
        var redirectUrl = '<?php echo $this->getRedirectUrl(); ?>';

        $('soisy-overlay').show();

        setTimeout(function () {
            location.replace(redirectUrl);
        }, 2000);
    });
</script>
<style>
    .soisy-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 5000;
        background-color: #fff;
        text-align: center;
        padding-top: 200px;
        font-size: 20px;
    }
</style>