<?php
/* @var $this Bitbull_Soisy_Block_Form_Soisy */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php $description = Mage::getStoreConfig(Bitbull_Soisy_Helper_Data::XML_PATH_DESCRIPTION) ?>
    <?php if (isset($description)): ?>
        <li>
            <p><?php echo $description ?></p>
        </li>
    <?php endif; ?>
    <li>
        <label for="soisy_instalment" class="required"><em>*</em><?php echo $this->__('Instalments number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="soisy_instalment" name="payment[instalment]"
                        title="<?php echo $this->helper('core')->quoteEscape($this->__('Instalments number')) ?>"
                        class="validate-select required-entry">
                    <option value=""><?php echo $this->__('Please select instalment') ?></option>
                </select>
            </div>
            <div class="v-fix">
                <p class="soisy_instalment_monthly_payment" style="padding-top: 3px;"></p>
            </div>
        </div>
    </li>

    <li>
        <label for="soisy_name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_address" name="payment[name]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Name')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('name')) ? $this->getAdditionalInformation('name') : $this->getBillingAddress()->getFirstname()) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_lastname" class="required"><em>*</em><?php echo $this->__('Lastname') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_lastname" name="payment[lastname]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Lastname')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('lastname')) ? $this->getAdditionalInformation('lastname') : $this->getBillingAddress()->getLastname()) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_address" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_address" name="payment[address]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Address')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('address')) ? $this->getAdditionalInformation('address') : $this->helper('soisy')->getBillingAddressWithoutCivicNumber($this->getBillingAddress()->getStreetFull())) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_civic_number" class="required"><em>*</em><?php echo $this->__('Civic Number') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_civic_number" name="payment[civic_number]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Civic Number')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml( ($this->getAdditionalInformation('civicNumber')) ? $this->getAdditionalInformation('civicNumber') : $this->helper('soisy')->getCivicFromBillingAddress($this->getBillingAddress()->getStreetFull()) ) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_postal_code" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_postal_code" name="payment[postcode]"
                   title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>"
                   class="input-text required-entry validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('postalCode')) ? $this->getAdditionalInformation('postalCode') : $this->getBillingAddress()->getPostcode()) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_city" name="payment[city]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('City')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml($this->getAdditionalInformation('city') ? $this->getAdditionalInformation('city') : $this->getBillingAddress()->getCity()) ?>"/>
        </div>
    </li>
    <li>
        <label for="soisy_region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
        <div class="input-box">
            <select id="soisy_region_id" name="payment[region_id]"
                    title="<?php echo $this->helper('core')->quoteEscape($this->__('State/Province')) ?>"
                    class="validate-select required-entry" style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                $('soisy_region_id').setAttribute('defaultValue',  "<?php echo ($this->getAdditionalInformation('region_id')) ? $this->getAdditionalInformation('region_id') : $this->getBillingAddress()->getRegionId() ?>");
                //]]>
            </script>
            <input type="text" id="soisy_region" name="payment[province]"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('province')) ? $this->escapeHtml($this->getAdditionalInformation('province')) : $this->getBillingAddress()->getRegion()) ?>"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('State/Province')) ?>"
                   class="input-text  required-entry<?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
                   style="display:none;"/>
        </div>
    </li>
    <li>
        <label for="soisy_mobile_phone" class="required"><em>*</em><?php echo $this->__('Mobile Phone') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_mobile_phone" name="payment[mobile_phone]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Mobile Phone')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml(($this->getAdditionalInformation('mobilePhone')) ? $this->getAdditionalInformation('mobilePhone') : $this->getBillingAddress()->getTelephone()) ?>"/>
        </div>
    </li>

    <?php if ($this->helper('customer/address')->isVatAttributeVisible()): ?>
        <li>
            <label for="soisy_vat_id"><?php echo $this->__('VAT Number') ?></label>

            <div class="input-box">
                <input type="text" id="soisy_vat_id" name="payment[vat_id]"
                       value="<?php echo $this->escapeHtml($this->getBillingAddress()->getVatId()) ?>"
                       title="<?php echo $this->helper('core')->quoteEscape($this->__('VAT Number')) ?>"
                       class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>"/>
            </div>
        </li>
    <?php endif; ?>

    <li>
        <label for="soisy_fiscal_code" class="required"><em>*</em><?php echo $this->__('Fiscal Code') ?></label>
        <div class="input-box">
            <input type="text" id="soisy_fiscal_code" name="payment[fiscal_code]"
                   title="<?php echo $this->helper('core')->quoteEscape($this->__('Fiscal code')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $this->escapeHtml($this->getAdditionalInformation('fiscalCode')) ?>"/>
        </div>
    </li>
    <li>
        <input type="checkbox" id="soisy_terms_and_conditions" name="payment[terms_and_conditions]"
               class="required-entry checkbox"
               title="<?php echo $this->__('Terms and Conditions') ?>" value="0"/>
        <label for="soisy_terms_and_conditions"
               class="required"><em>*</em><?php echo $this->__(' I Agree submitting the info to Soisy page') ?> <?php if ($link = Mage::getStoreConfig(Bitbull_Soisy_Helper_Data::XML_PATH_TERMS_AND_CONDITIONS)): ?>
                <a style="margin-top: 0;" target="_blank"
                   href="<?php echo $link ?>"><?php echo $this->__('Reed more') ?></a> <?php endif; ?></label>
    </li>
</ul>
<script type="text/javascript">
    //<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'soisy_region', 'soisy_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'soisy_postal_code');
    var soisyInstalmentSelector = new InstalmentSelector(
        'soisy_instalment',
        <?php echo $this->helper('soisy')->getInstalmentPeriodJson(Mage::getModel('checkout/session')->getQuote()->getGrandTotal()); ?> ,
        "<?php echo Mage::getUrl('soisy/loanQuote/amountbyinstalment'); ?>" ,
        "<?php echo Mage::getModel('checkout/session')->getQuote()->getGrandTotal() * 100; ?>",
        '.soisy_instalment_monthly_payment',
        "<?php echo __('per month.')?>"
        );
    //]]>
</script>
