<?php
/* @var $this Bitbull_Soisy_Block_Info_Soisy */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<p><strong><?php echo $this->__('Fiscal Code:') ?></strong> <span class="nobr"><?php echo $this->escapeHtml($this->getFiscalCode()) ?></span></p>
<p><strong><?php echo $this->__('Mobile Phone:') ?></strong> <span class="nobr"><?php echo $this->escapeHtml($this->getMobilePhone()) ?></span></p>
<p><strong><?php echo $this->__('Civic Number:') ?></strong> <span class="nobr"><?php echo $this->escapeHtml($this->getCivicNumber()) ?></span></p>
