<?php
/**
 * @category Bitbull
 * @package  Bitbull_Soisy
 * @author   Martins Saukums <martins.saukums@bitbull.it>
 */
?>

<?php $methods = $payments = Mage::getSingleton('payment/config')->getActiveMethods(); ?>

<?php if (array_key_exists(Bitbull_Soisy_Model_Soisy::METHOD_CODE, $methods)): ?>
    <script type="application/javascript">
        new soisyInstalmentBlock(
            "<?php echo Mage::getModel('checkout/session')->getQuote()->getGrandTotal() ?>",
            "<?php echo Mage::getUrl('soisy/loanQuote/amount') ?>",
            "<?php echo Mage::getStoreConfig('payment/soisy/cart_loan_quote_placement', Mage::app()->getStore()) ?>",
            "payment/soisy/loan_quote_text_cart"
        );
    </script>
<?php endif; ?>